sudo: required
services:
  - docker

before_install:
  - docker build -t kimjigabk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kimjigabk/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-252976436709"
  bucket_path: "docker"
  #same as app name.
  on:
    branch: master
    #feature branch에 가는건 디플로이 안되도록하는거임
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  #bucket: S3 Bucket, copy all my file from github and zip 
  #Docker-env.zqc2z76nn9.us-east-2.elasticbeanstalk.com 